CREATE TABLE IF NOT EXISTS DATAVERSEMETADATABLOCKFACET (
    ID  SERIAL NOT NULL, dataverse_id BIGINT NOT NULL,
    metadatablock_id BIGINT NOT NULL,
    DISPLAYORDER INTEGER NOT NULL, PRIMARY KEY (ID)
);
